- name: Install updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      - Updates
    state: installed
    log_path: C:\ansible_wu.txt
  register: update_result

- name: Reboot the system if needed
  win_reboot:
  when: update_result.reboot_required

- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest

- name: Install default software
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - firefox
    - sublimetext3
    - thunderbird
    - libreoffice
    - keepass
    - 7zip
  when: default_setup

- name: Install common dev software
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - conemu
    - visualstudiocode
  when: dev_c_sharp or dev_vm or dev_web

- name: Install C# dev software
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - visualstudio2017community
    - xamarin-visualstudio
  when: dev_c_sharp

- name: Install web dev software
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - pycharm-community
    - python
    - python2
    - googlechrome
  when: dev_web

- name: Install vm setup software
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - vagrant
    - virtualbox
  when: dev_vm

- name: Install other software
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - vlc
    - calibre
    - steam
    - mumble
    - teamspeak
  when: extented_setup
